apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  labels:
    app: elastic
spec:
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: elasticsearch:7.9.3
          env:
            - name: discovery.type
              value: single-node
            - name: http.port
              value: "8005"
          ports:
            - containerPort: 8005 
---

apiVersion: v1
kind: Service
metadata:
  name: elastic
spec:
  selector:
    app: elastic
  type: ClusterIP
  ports:
    - port: 8005
      targetPort: 8005