apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.9.3
        ports:
        - containerPort: 8005
        env:
        - name:  discovery.type
          value: single-node
        - name:  http.port
          value: "8005"

---

apiVersion: v1
kind: Service
metadata:
  name:  elasticsearch-service
spec:
  selector:
    app:  elasticsearch
  type: LoadBalancer
  ports:
  - protocol: TCP
    port:  8005
    targetPort:  8005
    nodePort: 30000