apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
  labels:
    app: grpc
spec:
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
        - name: grpc
          image: vladislavzhuk/grpc
          env:
            - name: GRPC_PORT
              value: "8001"
            - name: TYPE_STORAGE
              value: elasticsearch
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: grpc
spec:
  type: ClusterIP
  selector:
    app: grpc
  ports:
    - port: 8001
      targetPort: 8001