apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
  labels:
    app: grpc
spec:
  selector:
    matchLabels:
      app: grpc

  template:
    metadata:
      labels:
        app: grpc

    spec:
      containers:
        - name: elastic
          image: elasticsearch:7.9.3
          env:
            - name: discovery.type
              value: single-node
            - name: http.port
              value: "8005"
          ports:
            - containerPort: 8005

        - name: grpc
          image: vladislavzhuk/grpc
          env:
            - name: GRPC_PORT
              value: "8001"
            - name: TYPE_STORAGE
              value: elasticsearch
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: grpc
spec:
  type: ClusterIP
  selector:
    app: grpc
  ports:
    - name: grpc
      port: 8001
      targetPort: 8001

    - name: elastic
      port: 8005
      targetPort: 8005
