apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
  labels:
    app: http
spec:
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: http
          image: vladislavzhuk/http
          env:
            - name: SERVER_PORT
              value: "8000"
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: http
spec:
  selector:
    app: http
  type: LoadBalancer
  ports:
    - name: name-of-the-port
      port: 8000
      targetPort: 8000
      nodePort: 30000
